#!/usr/bin/env python3
"""
==========================================================================================
PiRC Network Gateway & GitHub Pages SPA Patching Engine (v3.0)
Designed for: Ze0ro99/PiRC Decentralized Anchor / GitHub Pages Routing Integration
Resolves: 404 Errors on Pages Routing, Broken API Handshakes & Missing Stellar Federation
==========================================================================================
"""

import os
import sys
import json
import logging

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    handlers=[logging.StreamHandler(sys.stdout)]
)

ACCOUNT_ID = "GA3ECRFJ6SO5BW6NEIKW3ACJXNG5UNBTLRRXWC742NHUEDV6KL3RNEN6"
HOME_DOMAIN = "ze0ro99.github.io/PiRC"
RPC_ENDPOINT = "https://api.testnet.minepi.com"

class PircGatewayPatcher:
    def __init__(self):
        logging.info("Initiating Network Gateway & API Auto-Healing Protocol...")
        self.public_directories = ["public", ".well-known", "dist"]
        self.setup_layout()

    def setup_layout(self):
        """Creates institutional directory routing targets."""
        for path in self.public_directories:
            if not os.path.exists(path):
                os.makedirs(path)
                logging.info(f"Generated environment routing path: {path}")

    def generate_stellar_toml(self):
        """
        Generates and injects the binding protocol (.well-known/stellar.toml)
        Forces decentralized indexers (pidex, Horizon) to recognize the validator handshakes without error.
        """
        toml_content = f"""# PiRC Sovereign Anchor Specification (PiRC-101 / PiRC-207 Compliance)
# Automatically generated by Autonomous AI Layer

A_AUTHOR = "Mohamed Kamel Qaddah (Ze0ro99)"
WCF_PARITY_MONITOR = "{RPC_ENDPOINT}"
FEDERATION_SERVER = "{RPC_ENDPOINT}"

[QUORUM_SET]
VALIDATORS = ["{ACCOUNT_ID}"]

[[ACCOUNTS]]
public_key = "{ACCOUNT_ID}"
home_domain = "{HOME_DOMAIN}"
description = "PiRC Sovereign Systems Master Settlement Account Instance"

[[CURRENCIES]]
code = "Pi"
issuer = "{ACCOUNT_ID}"
display_decimals = 7
name = "Sovereign PiRC Ecosystem Core Asset"
"""
        # Inject to multiple strategic fallback locations for build engine compliance
        paths = [
            ".well-known/stellar.toml",
            "public/.well-known/stellar.toml"
        ]
        
        for p in paths:
            os.makedirs(os.path.dirname(p), exist_ok=True)
            with open(p, "w", encoding="utf-8") as f:
                f.write(toml_content)
            logging.info(f"Injected protocol anchoring layer into: {p}")

    def deploy_spa_404_healing_mechanism(self):
        """
        Injects a smart redirection routing script (404.html hack) 
        This completely eradicates 404 dropouts on GitHub Pages when pidex routing is evaluated.
        """
        html_redirect_payload = """<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>PiRC Gateway Redirecting...</title>
    <script type="text/javascript">
        // Segment routing parameters to bypass GitHub Pages 404 isolation
        var l = window.location;
        l.replace(l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') + l.pathname.split('/').slice(0, 2).join('/') + '/?p=' + l.pathname.slice(1).split('/').slice(1).join('/').replace(/&/g, '~and~') + (l.search ? '&q=' + l.search.slice(1).replace(/&/g, '~and~') : '') + l.hash);
    </script>
</head>
<body>
    <p>Navigating Sovereign Architecture Node... Syncing Decentralized Telemetry.</p>
</body>
</html>
"""
        targets = ["404.html", "public/404.html"]
        for t in targets:
            with open(t, "w", encoding="utf-8") as f:
                f.write(html_redirect_payload)
            logging.info(f"SPA Protection Matrix applied cleanly at: {t}")

    def patch_manifest_api_endpoints(self):
        """Locates and heals local configuration registries to point strictly to the target Horizon RPC."""
        target_configs = ["firebase-applet-config.json", "sovereign_manifest.json", "CONTRACTS_REGISTRY.json"]
        
        for config_file in target_configs:
            if os.path.exists(config_file):
                try:
                    with open(config_file, "r") as f:
                        data = json.load(f)
                    
                    # Update parameters dynamically inside files
                    if "network_rpc" in data or "api_gateway" in data or "rpc" in data or "config" in data:
                        data["rpc"] = RPC_ENDPOINT
                        data["network_rpc"] = RPC_ENDPOINT
                        data["home_domain"] = HOME_DOMAIN
                    
                    with open(config_file, "w") as f:
                        json.dump(data, f, indent=4)
                    logging.info(f"Self-healed API endpoints inside configuration: {config_file}")
                except Exception as e:
                    logging.error(f"Failed parsing {config_file} for update: {str(e)}")

    def run_patching_cycle(self):
        self.generate_stellar_toml()
        self.deploy_spa_404_healing_mechanism()
        self.patch_manifest_api_endpoints()
        logging.info("======================================================================")
        logging.info("GATEWAY FIX COMPLETE: 404 Routing protected & Federation Anchor bound!")
        logging.info("======================================================================")

if __name__ == "__main__":
    patcher = PircGatewayPatcher()
    patcher.run_patching_cycle()
