/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SovereignRouteImport } from './routes/sovereign'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as MonetaryRouteImport } from './routes/monetary'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as JusticeRouteImport } from './routes/justice'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as AlphaHubRouteImport } from './routes/alpha-hub'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesOrderIdRouteImport } from './routes/services.$orderId'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SovereignRoute = SovereignRouteImport.update({
  id: '/sovereign',
  path: '/sovereign',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const MonetaryRoute = MonetaryRouteImport.update({
  id: '/monetary',
  path: '/monetary',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const JusticeRoute = JusticeRouteImport.update({
  id: '/justice',
  path: '/justice',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphaHubRoute = AlphaHubRouteImport.update({
  id: '/alpha-hub',
  path: '/alpha-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesOrderIdRoute = ServicesOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alpha-hub': typeof AlphaHubRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/governance': typeof GovernanceRoute
  '/justice': typeof JusticeRoute
  '/markets': typeof MarketsRoute
  '/matrix': typeof MatrixRoute
  '/monetary': typeof MonetaryRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/sovereign': typeof SovereignRoute
  '/sync': typeof SyncRoute
  '/wallet': typeof WalletRoute
  '/services/$orderId': typeof ServicesOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alpha-hub': typeof AlphaHubRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/governance': typeof GovernanceRoute
  '/justice': typeof JusticeRoute
  '/markets': typeof MarketsRoute
  '/matrix': typeof MatrixRoute
  '/monetary': typeof MonetaryRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/sovereign': typeof SovereignRoute
  '/sync': typeof SyncRoute
  '/wallet': typeof WalletRoute
  '/services/$orderId': typeof ServicesOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alpha-hub': typeof AlphaHubRoute
  '/contracts': typeof ContractsRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/governance': typeof GovernanceRoute
  '/justice': typeof JusticeRoute
  '/markets': typeof MarketsRoute
  '/matrix': typeof MatrixRoute
  '/monetary': typeof MonetaryRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/sovereign': typeof SovereignRoute
  '/sync': typeof SyncRoute
  '/wallet': typeof WalletRoute
  '/services/$orderId': typeof ServicesOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alpha-hub'
    | '/contracts'
    | '/dashboard'
    | '/developers'
    | '/governance'
    | '/justice'
    | '/markets'
    | '/matrix'
    | '/monetary'
    | '/resources'
    | '/services'
    | '/sovereign'
    | '/sync'
    | '/wallet'
    | '/services/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alpha-hub'
    | '/contracts'
    | '/dashboard'
    | '/developers'
    | '/governance'
    | '/justice'
    | '/markets'
    | '/matrix'
    | '/monetary'
    | '/resources'
    | '/services'
    | '/sovereign'
    | '/sync'
    | '/wallet'
    | '/services/$orderId'
  id:
    | '__root__'
    | '/'
    | '/alpha-hub'
    | '/contracts'
    | '/dashboard'
    | '/developers'
    | '/governance'
    | '/justice'
    | '/markets'
    | '/matrix'
    | '/monetary'
    | '/resources'
    | '/services'
    | '/sovereign'
    | '/sync'
    | '/wallet'
    | '/services/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlphaHubRoute: typeof AlphaHubRoute
  ContractsRoute: typeof ContractsRoute
  DashboardRoute: typeof DashboardRoute
  DevelopersRoute: typeof DevelopersRoute
  GovernanceRoute: typeof GovernanceRoute
  JusticeRoute: typeof JusticeRoute
  MarketsRoute: typeof MarketsRoute
  MatrixRoute: typeof MatrixRoute
  MonetaryRoute: typeof MonetaryRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SovereignRoute: typeof SovereignRoute
  SyncRoute: typeof SyncRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sovereign': {
      id: '/sovereign'
      path: '/sovereign'
      fullPath: '/sovereign'
      preLoaderRoute: typeof SovereignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monetary': {
      id: '/monetary'
      path: '/monetary'
      fullPath: '/monetary'
      preLoaderRoute: typeof MonetaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/justice': {
      id: '/justice'
      path: '/justice'
      fullPath: '/justice'
      preLoaderRoute: typeof JusticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alpha-hub': {
      id: '/alpha-hub'
      path: '/alpha-hub'
      fullPath: '/alpha-hub'
      preLoaderRoute: typeof AlphaHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$orderId': {
      id: '/services/$orderId'
      path: '/$orderId'
      fullPath: '/services/$orderId'
      preLoaderRoute: typeof ServicesOrderIdRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesOrderIdRoute: typeof ServicesOrderIdRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesOrderIdRoute: ServicesOrderIdRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlphaHubRoute: AlphaHubRoute,
  ContractsRoute: ContractsRoute,
  DashboardRoute: DashboardRoute,
  DevelopersRoute: DevelopersRoute,
  GovernanceRoute: GovernanceRoute,
  JusticeRoute: JusticeRoute,
  MarketsRoute: MarketsRoute,
  MatrixRoute: MatrixRoute,
  MonetaryRoute: MonetaryRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SovereignRoute: SovereignRoute,
  SyncRoute: SyncRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
