#!/bin/bash
# ==============================================================================
# PiRC Master Orchestrator & Synchronization Engine
# Network: Pi Testnet / Stellar Testnet
# Standard: PiRC-101, PiRC-207 (7-Layer RWA Ecosystem)
# ==============================================================================

set -e

echo "🚀 [PiRC Orchestrator] Initializing Master Synchronization Process..."

# --- 1. Define Master Data (From Official RAW Records) ---
ISSUER_ACCOUNT="GA3ECRFJ6S05BW6NEIKW3ACJXNG5UNBTLRRXWC742NHUEDV6KL3RNEN6"
REGISTRY_CONTRACT="CAEUNHEUXACISTVHICFNISFRTRVSK5IALA3H5MUT7P4JKU5L3IPSKG4B"
HOME_DOMAIN="ze0ro99.github.io/PiRC"
NETWORK_PASSPHRASE="Pi Testnet"
HORIZON_URL="https://api.testnet.minepi.com"
RPC_URL="https://testnet.sorobanrpc.com"

declare -A LAYER_CONTRACTS=(
    ["BLUE"]="CAMSQZTSCTF3MG4UEIAWKRZNSX7LLKGKXMVBEQO2ETVPGS3CINM7JBQD"
    ["GOLD"]="CD3UAUN4FU3VHPMLOZWFQWJ2UBUUBBD37SZ7WBEGJQACJ7YF6QVE2SYG"
    ["GREEN"]="CBPG33E7RUX6MGU65IMM4HXCAGLA4OZRBOUWKQSBTIZWE2RD52VGWDT4"
    ["ORANGE"]="CB7T6TDSZ5B2MQI7NI4EG6ZASYPRMJ3XVUWS6BON4Z64OBMUJ4ZD6GKF"
    ["PURPLE"]="CCGEMIEAZFJSBTRL5VGJJAUGPJI3B7UQ3BTAB2OQGW73JMWLS57YVVA4"
    ["RED"]="CC6WMAHKOPWY6HW46VNKTAV4DZZLRTTNMYLDEKCAICQGMCWV5PZYNTBO"
    ["YELLOW"]="CANLSQUPUZYKE3S2HAIGXAHMOQWE4FVX5DS7GTL42BVKSNHLFVMQSDFF"
)

# --- 2. Create Required Directories ---
mkdir -p scripts/deploy scripts/run archive/backups archive/logs 
mkdir -p schemas assets/js .well-known contracts/soroban/src

# --- 3. Safe Repository Organization (NO DELETION) ---
echo "🧹 [PiRC Orchestrator] Organizing root directory safely..."
find . -maxdepth 1 -name "deploy_*.sh" -exec mv {} scripts/deploy/ \; 2>/dev/null || true
find . -maxdepth 1 -name "run_*.sh" -exec mv {} scripts/run/ \; 2>/dev/null || true
find . -maxdepth 1 -name "finalize_*.sh" -exec mv {} scripts/deploy/ \; 2>/dev/null || true
find . -maxdepth 1 -name "*.backup*" -exec mv {} archive/backups/ \; 2>/dev/null || true
find . -maxdepth 1 -name "*.log" -exec mv {} archive/logs/ \; 2>/dev/null || true

# --- 4. Data Injection: Frontend & Schemas ---
echo "🔄 [PiRC Orchestrator] Injecting 7-Layer data..."

cat <<JSON_EOF > schemas/pirc207_layers.json
{
  "standard": "PiRC-207",
  "network": "$NETWORK_PASSPHRASE",
  "rpc_endpoint": "$RPC_URL",
  "master_registry": "$REGISTRY_CONTRACT",
  "issuer": "$ISSUER_ACCOUNT",
  "layers": {
    "L0_PURPLE": { "address": "${LAYER_CONTRACTS[PURPLE]}", "role": "Root Registry" },
    "L1_GOLD": { "address": "${LAYER_CONTRACTS[GOLD]}", "role": "Reserve Asset" },
    "L2_YELLOW": { "address": "${LAYER_CONTRACTS[YELLOW]}", "role": "Utility Tier" },
    "L3_ORANGE": { "address": "${LAYER_CONTRACTS[ORANGE]}", "role": "Settlement" },
    "L4_BLUE": { "address": "${LAYER_CONTRACTS[BLUE]}", "role": "Liquidity" },
    "L5_GREEN": { "address": "${LAYER_CONTRACTS[GREEN]}", "role": "PiCash" },
    "L6_RED": { "address": "${LAYER_CONTRACTS[RED]}", "role": "Governance" }
  },
  "last_updated": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
}
JSON_EOF

cat <<JS_EOF > assets/js/constants.js
// Auto-generated by PiRC Master Orchestrator
export const PIRC_CONFIG = {
    ISSUER_ACCOUNT: "$ISSUER_ACCOUNT",
    REGISTRY_CONTRACT: "$REGISTRY_CONTRACT",
    HOME_DOMAIN: "$HOME_DOMAIN",
    NETWORK_PASSPHRASE: "$NETWORK_PASSPHRASE",
    HORIZON_URL: "$HORIZON_URL",
    RPC_URL: "$RPC_URL"
};

export const TOKEN_LAYERS = {
    BLUE: "${LAYER_CONTRACTS[BLUE]}",
    GOLD: "${LAYER_CONTRACTS[GOLD]}",
    GREEN: "${LAYER_CONTRACTS[GREEN]}",
    ORANGE: "${LAYER_CONTRACTS[ORANGE]}",
    PURPLE: "${LAYER_CONTRACTS[PURPLE]}",
    RED: "${LAYER_CONTRACTS[RED]}",
    YELLOW: "${LAYER_CONTRACTS[YELLOW]}"
};
JS_EOF

# --- 5. Generate Official pi.toml Metadata ---
cat <<TOML_EOF > .well-known/pi.toml
# PiRC-207 Official Metadata
VERSION="2.0.0"
NETWORK_PASSPHRASE="$NETWORK_PASSPHRASE"

[DOCUMENTATION]
ORG_NAME="PiRC Ecosystem"
ORG_URL="https://$HOME_DOMAIN"
ORG_DESCRIPTION="Professional 7-Layer RWA Ecosystem on Pi Network"
ORG_OFFICIAL_EMAIL="admin@$HOME_DOMAIN"

[[PRINCIPALS]]
name="Ze0ro99"
email="admin@$HOME_DOMAIN"

[[CURRENCIES]]
code="GOLD"
issuer="$ISSUER_ACCOUNT"
display_decimals=7
name="PiRC Reserve Asset"
desc="Primary reserve currency with a Parity of 314,159."
status="live"

[[CURRENCIES]]
code="GREEN"
issuer="$ISSUER_ACCOUNT"
display_decimals=7
name="PiCash"
desc="Official ecosystem currency for P2P and merchant use."
status="live"
TOML_EOF

echo "🎉 [PiRC Orchestrator] Master Synchronization Complete!"
